In [2]:
import pickle
import torch

In [67]:
with open('../data/tsp/val_cost.pkl', 'rb') as file:
    data = pickle.load(file)
cost = [torch.FloatTensor(x) for x in data]

with open('../data/tsp/val_location.pkl', 'rb') as file:
    data = pickle.load(file)
location = [torch.FloatTensor(x) for x in data]

5000

In [64]:
a = torch.tensor([])
b = torch.cat((a, torch.LongTensor([1,2,3,4])), dim=0)
torch.cat((b, torch.tensor([1,2,3,4,5,6])), dim=0)
b

tensor([1., 2., 3., 4.])

In [50]:
a = torch.tensor([])
b=torch.cat((a, torch.LongTensor([[1,2,3,4], [4,5,6,7]])), dim=0)#[1:]
b
torch.cat((b, torch.LongTensor([[1,2,3,4], [9,8,7,9]])), dim=0)

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.],
        [1., 2., 3., 4.],
        [9., 8., 7., 9.]])

In [9]:
# Original 2D tensor
tensor_2d = torch.tensor([
    [1, 4, 6, 5, 0, 9, 7, 8],
    [3, 0, 2, 6, 1, 7, 5, 4],
    [8, 5, 0, 3, 2, 1, 4, 7]
])

# Function to shift each row from the value 0 onwards
def shift_row(row):
    zero_index = (row == 0).nonzero(as_tuple=True)[0].item()
    part1 = row[zero_index:]  # From value 0 to the end
    part2 = row[:zero_index]  # From the beginning to value 0
    return torch.cat((part1, part2))

# Apply the function to each row and stack the results
new_tensor_2d = torch.stack([shift_row(row) for row in tensor_2d])

print(new_tensor_2d)

tensor([[0, 9, 7, 8, 1, 4, 6, 5],
        [0, 2, 6, 1, 7, 5, 4, 3],
        [0, 3, 2, 1, 4, 7, 8, 5]])


In [8]:
new_tensor_2d.tolist()

[[9, 7, 8, 1, 4, 6, 5, 0], [7, 5, 4, 3, 0, 2, 6, 1], [8, 5, 0, 3, 2, 1, 4, 7]]

In [57]:
torch.cat([torch.tensor([1,2]), torch.tensor([3,4])], 0)

tensor([1, 2, 3, 4])

In [ ]:
# function used for shifting the tour so that 0 is the starting point (depot)
        def shift_row(row, by='min'):
            if by == 'min':
                zero_index = (row.min()).nonzero(as_tuple=True)[0].item()
            elif by == 'max':
                
                zero_index = (row.max()).nonzero(as_tuple=True)[0].item()
            else:
                zero_index = (row == 0).nonzero(as_tuple=True)[0].item()
            part1 = row[zero_index:]  # From value 0 to the end
            part2 = row[:zero_index]  # From the beginning to value 0
            return torch.cat((part1, part2))
        
        if self.problem == 'tsp':
            ret_sequences = torch.stack([shift_row(row, by='min') for row in ret_sequences])
            ret_outpus    = torch.stack([shift_row(row, by='max') for row in ret_outpus])

In [70]:
import random
a = [[1,2,3], [4,5,6], [7,8,9]]
b = [4,7,8]
temp = list(zip(location[:2], cost[:2]))
random.shuffle(temp)
res1, res2 = zip(*temp)
# res1 and res2 come out as tuples, and so must be converted to lists.
a, b = list(res1), list(res2)


In [76]:
a[0][:5]

tensor([[52.3238,  4.9279],
        [52.3791,  4.8790],
        [52.3797,  4.8793],
        [52.3798,  4.8794],
        [52.3800,  4.8796]])

In [79]:
location[1][:5]

tensor([[52.3238,  4.9279],
        [52.3791,  4.8790],
        [52.3797,  4.8793],
        [52.3798,  4.8794],
        [52.3800,  4.8796]])

In [81]:
cost[0][:5][:,:5]

tensor([[  0.0000, 630.6000, 649.4000, 655.8000, 653.8000],
        [  0.0000,   0.0000,  18.8000,  25.2000,  23.2000],
        [  0.0000,  49.7000,   0.0000,   6.4000,   4.4000],
        [  0.0000,  53.1000,   6.4000,   0.0000,   2.0000],
        [  0.0000,  54.1000,   4.4000,   2.0000,   0.0000]])

In [82]:
b[1][:5][:,:5]

tensor([[  0.0000, 630.6000, 649.4000, 655.8000, 653.8000],
        [  0.0000,   0.0000,  18.8000,  25.2000,  23.2000],
        [  0.0000,  49.7000,   0.0000,   6.4000,   4.4000],
        [  0.0000,  53.1000,   6.4000,   0.0000,   2.0000],
        [  0.0000,  54.1000,   4.4000,   2.0000,   0.0000]])

In [5]:
with open('../results/tsp/eval_location/eval_location-tsp_100_tsp100_rollout_20240518T191846-greedy-t1-0-5000.pkl', 'rb') as f:
    data = pickle.load(f)

data

([(1923.6998,
   [0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
    89,
    90,
    91,
    92,
    93,
    94,
    95,
    96,
    97,
    98,
    99],
   9.148452520370483),
  (2328.2998,
   [0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,


In [39]:
a = torch.tensor([[1,1,2,3], [4,5,6,7],[8,9,8,10]])
b = torch.tensor([])
b = torch.cat((b, a[0]), 0)
b = torch.cat((b, a[1]), 0)
b

tensor([1., 1., 2., 3., 4., 5., 6., 7.])

In [51]:
import pickle
with open('../results/tsp/val_location/val_location-tsp_100_tsp100_rollout_20240520T191606-greedy-t1-0-5000.pkl', 'rb') as f:
    data = pickle.load(f)


[(5583.6,
  [0,
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99],
  20.46982741355896),
 (2381.6,
  [0,
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   3

In [56]:
data[0][0]

(5583.6,
 [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99],
 20.46982741355896)